name: env_zoo_calrissian
channels:
  - terradue
  - conda-forge
  - eoepca
dependencies:
  - python==3.10
  - black
  - pre-commit
  - isort
  - flake8
  - autoflake
  - pylint
  - nose2
  - pip
  - loguru
  - pip:
    - git+https://github.com/EOEPCA/zoo-calrissian-runner.git@feature/using-jobid-namespace
    - attrs
    - cwl-utils==0.14
    - kubernetes==28.1.0
    - cookiecutter
    - boto3
    - botocore
    - pystac
    - python-dotenv
    - pyjwt
